# Generated by Django 4.2.4 on 2023-08-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False, editable=False)),
                ('is_superuser', models.BooleanField(default=False, editable=False)),
                ('api_key', models.CharField(default='JrfdwlVqObsh2EtP1OU77vvQGAP1GW2247_l7pd3syQ', editable=False, max_length=500, unique=True)),
                ('avatar', models.ImageField(blank=True, default='assets/avatars/avatar_leopard.png', null=True, upload_to='users/avatars/%Y/%m/')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined', 'username', 'email'],
            },
        ),
    ]
