# Generated by Django 4.2.4 on 2023-08-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='EI_LFeVTLLa9UmTeFVHskKp1AY-IMf1RkOF1DqW0QHc', editable=False, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='assets/avatars/avatar_dog.png', null=True, upload_to='users/avatars/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
