# Generated by Django 4.2.4 on 2023-08-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_api_key_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='gilzAUrqQOwMNe_FtlnVRmEm5rX6-RuxPpcQEI_q544', editable=False, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='assets/avatars/avatar_cat.png', null=True, upload_to='users/avatars/%Y/%m/'),
        ),
    ]
